runtime: python27
threadsafe: yes
api_version: 1

handlers:
- url: /bootstrap
  static_dir: bootstrap
- url: /images
  static_dir: images
- url: /.*
  script: main.app

  
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest